version: '3.7'

services:
    app:
        image: app
        container_name: notice-app
        build:
            context: ./
            dockerfile: ./docker/laravel.Dockerfile
            args:
                user: sammy
                uid: 1000
        volumes:
            - ./:/var/www/
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - notice_app

    nginx:
        image: nginx:1.17-alpine
        container_name: notice-nginx
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        restart: unless-stopped
        depends_on:
            - app
        networks:
            - notice_app
    db:
        image: mysql:8.0
        container_name: notice-db
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: notice_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: notice_user
            MYSQL_PASSWORD: notice_pass
            SERVICE_NAME: mysql
        networks:
            - notice_app
        volumes:
            - ./docker/database:/docker-entrypoint-initdb.d

networks:
    notice_app:
        driver: bridge